spring:
  application:
    name: tzc-simulator-coordinator

scheduling:
  default:
    cron: 0 */1 * * * ?

server:
  port: 4242
  servlet:
    context-path: /simulators

simulators:
  pixi:
    autostart: false
    files:
      path: 'c:\dev\tmp\'
      name: 'VehicleSimulationData.csv'
    server:
      host: localhost
      port: 2424