spring:
  application:
    name: tzc-simulator-coordinator

logging:
  level:
    org.springframework.integration: DEBUG

scheduling:
  default:
    cron: '-'

server:
  port: 4242
  servlet:
    context-path: /simulators

simulators:
  pixi:
    autostart: false
    files:
      path: '../src/main/resources/'
      name: 'VehicleSimulationData.csv'
    server:
      host: pixi-sim-service
      port: 3380
