spring:
  application:
    name: tzc-simulator-coordinator

logging:
  level:
    org.springframework.integration: INFO

scheduling:
  default:
    cron: '-'

server:
  port: 4242
  servlet:
    context-path: /simulators

simulators:
  files:
    path: '${TZC_SIM_DATA_PATH:../src/main/resources}'
    name: '${TZC_SIM_DATA_FILE:VehicleSimulationData.csv}'
  clients: [
    '${TZC_SIM_URL_0:localhost:1234}',
    '${TZC_SIM_URL_1:localhost:5678}'
  ]