apiVersion: batch/v1
kind: Job
metadata:
  name: tzc-simulator-coordinator-job
  namespace: tzc-test-ns
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: tzc-simulator-coordinator-container
        image: 211125768014.dkr.ecr.us-east-2.amazonaws.com/neotzc/simulator-coordinator:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            sleep 300;  # Keeps pod alive for 5 mins
            # Download the latest vehicle simulation data from S3 and replace the existing file
            aws s3 cp s3://vehicle-sim-data-temp/VehicleSimulationData.csv /app/src/main/resources/VehicleSimulationData.csv --overwrite

            # Run the application and log output
            java -jar /app/target/tzc-simulator-coordinator-1.0.jar \
              --spring.config.location=../src/main/resources/ \
              --spring.config.name=k8s-config run | tee -a /var/log/tzc-simulator.log;

            # Upload logs after the Job completes
            TIMESTAMP=$(date +%Y%m%d-%H%M%S);
            GZFILE=/tmp/coordinator-logs-$TIMESTAMP.log.gz;
            if [ -f /var/log/tzc-sim-coordinator.log ]; then
              gzip -c /var/log/tzc-sim-coordinator.log > $GZFILE;
              aws s3 cp $GZFILE s3://k8s-tzc-logs/logs/;
            else
              echo 'Log file not found, skipping upload.';
            fi

---
apiVersion: v1
kind: Service
metadata:
  name: tzc-simulator-coordinator-service  # Service name
  namespace: tzc-test-ns  # Namespace where the Service runs
spec:
  selector:
    app: tzc-simulator-coordinator  # Matches pods with this label to route traffic
  ports:
    - protocol: TCP  # Communication protocol
      port: 4242  # Port exposed by the service
      targetPort: 4242  # Port on the container that receives traffic
