apiVersion: batch/v1
kind: Job
metadata:
  name: tzc-simulator-coordinator-job
  namespace: tzc-test-ns
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: tzc-simulator-coordinator
    spec:
      restartPolicy: Never
      containers:
      - name: tzc-simulator-coordinator-container
        image: 211125768014.dkr.ecr.us-east-2.amazonaws.com/neotzc/simulator-coordinator:latest
        imagePullPolicy: Always
        args:
          - "/bin/bash"
          - "-c"
          - "java -jar /app/target/tzc-simulator-coordinator-1.0.jar --spring.config.location=../src/main/resources/ --spring.config.name=k8s-config run | tee -a /var/log/tzc-simulator.log"
        ports:
          - containerPort: 4242
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: tzc-simulator-coordinator-service  # Service name
  namespace: tzc-test-ns  # Namespace where the Service runs
spec:
  selector:
    app: tzc-simulator-coordinator  # Matches pods with this label to route traffic
  ports:
    - protocol: TCP  # Communication protocol
      port: 4242  # Port exposed by the service
      targetPort: 4242  # Port on the container that receives traffic
